
### Post Comminity(Success)


POST http://localhost:8080/communities/1
Authorization: Bearer test
Content-Type: application/json

{
    "cateId" : "1",

    "writerId" : "지인",

    "content" : "내용",

    "title" : "제목"
  
}


