
### Post Comminity(Success)


POST http://localhost:8080/communities
Authorization: Bearer test
Content-Type: application/json

{
    "cateId" : "1",
    "content" : "내용",
    "title" : "제목"
}





### Get Comminity(Success)


GET http://localhost:8080/communities
Authorization: Bearer test
Content-Type: application/json



