name: deploy

# main 브랜치에 push시 동작한다
on:
  push:
    branches: [main]
    
jobs:
  build:
    # 해당 동작들을 돌릴 OS
    runs-on: ubuntu-latest
    steps:
      # 실제 main branch에 push하면 동작할 내용들
      
      # dependencies 설치 
      # java 설치
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          
      # node 설치
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          
     
      # checkout 하기
      # backend
      - name: checkout backend
        uses: actions/checkout@v2
        
      # frontend
      - name: checkout frontend
        uses: actions/checkout@v2
        with:
          repository: skdksldk1485/mountain
          path: ./frontend

      
      # backend 폴더에 frontend 프로젝트 설치
      # build 하기
      - name: build frontend to resources
        run: |
          sh build.sh
          git remote -v 
      
      # heroku에 배포하기
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "mountain-couchcoding" #
          heroku_email: "jiinahn92@gmail.com"
